version: '3'
services:
  mongo:
    restart: unless-stopped
    image: mongo:4
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
  student_service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://localhost:27017
      DB_NAME: student_db
    ports:
      - "8080:8080"

